### ISSUE TITLE
Фича pipeline содержит ошибки при работе с параметром waitdev

### ISSUE THREAD

**Issue by lo1ol** [osboot/make-initrd#2]
Добрый день,

Мы недавно реализовывали загрузку системы с ro устройств и обнаружили небольшие недочеты при работе с параметром waitdev.

1. В этом месте функция *get_dev* иногда возвращает пустую строку в dev, но при этом возвращенное значение функции 0: https://github.com/osboot/make-initrd/blob/f23c53d170cd8b3570641681b85be5ab5f47f422/features/pipeline/data/lib/uevent/filters/pipeline-waitdev#L10-L12
Таким образом я бы добавил дополнительную проверку на наличие непустой dev строки:
```bash
	[ -z "$spec" ] ||
		get_dev dev "$spec" ||: [ -z "$dev" ] ||
	eval "export WAITDEV_FILE$WAITDEV_FILE=\"\$dev\""
```
2.  Файл _/.initrd/pipeline/waitdev_ постоянно перезаписывается: https://github.com/osboot/make-initrd/blob/f23c53d170cd8b3570641681b85be5ab5f47f422/features/pipeline/data/lib/uevent/filters/pipeline-waitdev#L19-L20
Таким образом построение оверлея над несколькими устройствами не возможно. Я бы переписал эту часть вот так:
```bash
environ -q -i 'WAITDEV_FILE*' >> waitdev
```
При таком подходе хоть в файл и записывается несколько раз значение *WAITDEV_FILE* , оно остается всегда постоянным и при выполнении команды *source* над этим файлом это не помешает его прочитать.  Также стоит учесть возможный момент одновременного записывания в файл, но он возможен и при текущей реализации (в файл _waitdev.env_). Также у меня есть ощущение, что при перенаправлении потоков с помощью _>>_ будут перемешиваться только строки, что тоже нас устраивает

После этих изменений загрузка с ro раздела происходила успешно. 

3. Также у меня была небольшая проблема при работе с устройствами, на которых изначально скрыты разделы. udevadm не возвращал для таких устройств переменные __ID_FS_UUID__, __ID_FS_LABEL__, __ID_PART_ENTRY_UUID__ и __ID_PART_ENTRY_NAME__, но зато для них была установлена переменная __ID_SERIAL__, можно ли добавить в существующую реализацию функции get_dev получения устройства по переменной __SERIAL__?

**Comment by legionus** [comment]
Вы используете make-initrd не на дистрибутиве altlinux ?

**Comment by legionus** [comment]
В данный момент я работаю над увеличением портабильности проекта.

> В этом месте функция get_dev иногда возвращает пустую строку в dev, но при этом возвращенное значение функции 0

Да, я столкнулся недавно с той же проблемой на fedora. В следующем релизе это будет исправлено. Проверка на пустоту должна быть в самой функции `get_dev`.

> Файл /.initrd/pipeline/waitdev постоянно перезаписывается:

Правильно ли понимаю, что вы хотите иметь возможность определять несколько `waitdev=` ?

> Также у меня была небольшая проблема при работе с устройствами, на которых изначально скрыты разделы. udevadm не возвращал для таких устройств переменные ID_FS_UUID, ID_FS_LABEL, ID_PART_ENTRY_UUID и ID_PART_ENTRY_NAME

Это случается если в образ не попадают необходимые системные правила udev. Это также будет скоро исправлено.

> зато для них была установлена переменная ID_SERIAL, можно ли добавить в существующую реализацию функции get_dev получения устройства по переменной SERIAL?

Интересная мысль. Можно попробовать.

**Comment by lo1ol** [comment]
1. я использую make-initrd на дистрибутиве altlinux
 2. В текущий момент использование более чем одного waitdev мне не пригождалось. Тем не менее сценарии использования нескольких waitdev у меня в голове возникают. 

Спасибо большое! Удобный продукт разрабатываете)

**Comment by legionus** [comment]
> Также у меня была небольшая проблема при работе с устройствами, на которых изначально скрыты разделы. udevadm не возвращал для таких устройств переменные ID_FS_UUID, ID_FS_LABEL, ID_PART_ENTRY_UUID и ID_PART_ENTRY_NAME

Хм... на альтлинуксе есть всегда нужные правила. Эти переменные должны быть доступны для блочного устройства с файловой системой.

**Comment by legionus** [comment]
>     2. В текущий момент использование более чем одного waitdev мне не пригождалось. Тем не менее сценарии использования нескольких waitdev у меня в голове возникают.

Для реализации этого мало просто писать в конец. Я попробую реализовать такой сценарий.

> Спасибо большое! Удобный продукт разрабатываете)

Спасибо :)

**Comment by lo1ol** [comment]
> Эти переменные должны быть доступны для блочного устройства с файловой системой.
Разобрался в чем дело. Почему-то мне казалось, что на устройствах с разделами UUID тоже присутствует, но кажется это не так. 

Например, на устройстве _/dev/sda_ есть 2 раздела:
1. _/dev/sda1_
2. _/dev/sda2_

И я думал, что у _/dev/sda_ тоже есть свой UUID, но это оказалось не так. Зато присутствует идентификатор **ID_SERIAL**, который позволяет идентифицировать устройство _/dev/sda_

**Comment by legionus** [comment]
`UUID` бывает только у файловой системы. Я добавил (пока не пушил) поддержку `root=SERIAL=*` на самом деле поддержка не только для параметра `root=`.

**Comment by lo1ol** [comment]
Понял, спасибо)

Кстати, вы не в курсе есть ли какие-то проблемы внедрения последней версии make-initrd в последние версии alt linux? Сейчас я использовал версию make-initrd 2.11, но есть возможности, которые доступны только в новых версиях: поиск по PARTUUID, будущий поиск по SERIAL и правки в pipeline.

Хотелось бы сразу ставить свежую версию make-initrd для реализации своих сценариев, а не вручную править использующиеся старые версии из пакетов.

**Comment by legionus** [comment]
Версия в сизифе содержит регрессию, которая будет исправлена в новом релизе. О других проблемах мне не известно.

**Comment by lo1ol** [comment]
хорошо

**Comment by legionus** [comment]
Попробуйте 2.14.0
