### ISSUE TITLE
Universal initrd

### ISSUE THREAD

**Issue by mikhailnov** [osboot/make-initrd#23]
Hello.
I want to make an universal initrd for ALT Linux on a USB SSD drive which would be able to boot on any hardware. That is what dracut is able to make. I could not find anything like that in make-initrd. Does such a mode exist?

**Comment by mikhailnov** [comment]
It is called "hostonly" in dracut. I want it to be not host-only.

**Comment by legionus** [comment]
@mikhailnov You mean the ability to put modules for more than one kernel in the initramfs?

**Comment by midyukov-anton** [comment]
> I want to make an universal initrd for ALT Linux on a USB SSD drive which would be able to boot on any hardware. That is what dracut is able to make. I could not find anything like that in make-initrd. Does such a mode exist?

https://github.com/osboot/make-initrd/commit/9de1abb36add79f3ff77738e476a6094b4427db7

**Comment by mikhailnov** [comment]
> @mikhailnov You mean the ability to put modules for more than one kernel in the initramfs?

No. I mean including such set of kernel modules that would make initrd suitable for a large set of hardware.
Anton suggested to use features 'sbc' and 'usb', they look like what I want.
