### ISSUE TITLE
Некорректное определение абсолютных символических ссылок

### ISSUE THREAD

**Issue by lo1ol** [osboot/make-initrd#3]
В этом месте не учитывается то, что ссылка может быть абсолютным путем:
https://github.com/osboot/make-initrd/blob/a116549a31cffdddee1d5e9c4968c6ac2171a753/utils/initrd-put/initrd-put.c#L263-L279

Проблему можно решить так:
```c
static void canonicalize_symlink(char *file, char *target, char *d)
{
	char pathbuf[PATH_MAX + 1];
	char *p;

	if (verbose > 2)
		warnx("canonicalize_symlink: %s", file);
        
        if (target && target[0] == '/') {
                strcpy(d, target);
                return;
        }
        
	strncpy(pathbuf, file, sizeof(pathbuf) - 1);
	if ((p = strrchr(pathbuf, '/'))) {
		p++;
		*p = 0;
	}
	strncat(pathbuf, target, sizeof(pathbuf) - 1 - strlen(pathbuf));

	canonicalize_path(pathbuf, d);
}

```

Словил проблему при запуске make-initrd на Ubuntu 20.04 вызванную этой багой

**Comment by legionus** [comment]
В чём проявляется проблема ? `canonicalize_path` всё равно нужен поскольку путь может быть вида `/usr/../bin/bash`.

**Comment by legionus** [comment]
Для меня тема портирования на другие дистрибутивы очень интересна. Большинство изменений текущего релиза были продиктованы портированием на fedora, но этот процесс ещё не завершён.

**Comment by lo1ol** [comment]
точно не могу сказать, т.к. полностью не разобрался в коде, но заметил, что абсолютные символические ссылки у меня разыменовывались некорректно,

Например, символическая ссылка */dir1/symlink -> /dir2/file* раскрывалось так */dir1/dir2/file*

Если функцию канонизации пути нужно оставить, то тогда можно преобразовать код таким образом:
```c
        if (target && target[0] == '/') {
                canonicalize_path(target, d);
                return;
        }
```

**Comment by legionus** [comment]
> Например, символическая ссылка /dir1/symlink -> /dir2/file раскрывалось так /dir1/dir2/file

Я посмотрю и постараюсь исправить.

**Comment by legionus** [comment]
Ваш патч частично правильный. Такое изменение позволит избежать ошибки, но в итоге скопированный силинк будет указывать не туда куда нужно. Это несколько другая проблема.

**Comment by lo1ol** [comment]
хорошо)
