### ISSUE TITLE
Support for live environments

### ISSUE THREAD

**Issue by firasuke** [osboot/make-initrd#32]
Hey there,

This project looks promising, and I was wondering if it actually supported booting in live environments (e.g. ISOs on CDs or USBs)?

I was also wondering if there is support for `overlayfs` and `squashfs` for compressed rootfs.

**Comment by legionus** [comment]
> This project looks promising, and I was wondering if it actually supported booting in live environments (e.g. ISOs on CDs or USBs)?

@firasuke This project creates an initramfs image that can be booted in different ways:

* via bootloader like a grub, lilo or something like that.
* via network by pxelinux for example.
* from CD/DVD by isolinux.

I mean that CD, network or disk partition is the location from where the image is loaded by other utilities. 

I'm not sure I understand what initramfs support you're talking about.

> I was also wondering if there is support for overlayfs and squashfs for compressed rootfs.

Yes. We have a module that allows to boot such configurations. I have a system where on a certain partition there is a squashfs image of the root file system and on top of which I mount overlayfs for copy-on-write. Everything that needs to be done is determined at the boottime via cmdline kernel parameters.

**Comment by firasuke** [comment]
I meant does the project support live hooks for booting ISOs? Does it detect if the root filesystem is on `/dev/sr0` or `/dev/disk/by-label/XXX`?

**Comment by legionus** [comment]
> I meant does the project support live hooks for booting ISOs? Does it detect if the root filesystem is on `/dev/sr0` or `/dev/disk/by-label/XXX`?

To be honest, I didn’t check it specifically from the CD. The make-initrd uses sysfs (/sys) to detect the modules needed to root filesystem. I think this will also work for booting from CD. If not, then I think such support can be added.

**Comment by firasuke** [comment]
> To be honest, I didn’t check it specifically from the CD. The make-initrd uses sysfs (/sys) to detect the modules needed to root filesystem. I think this will also work for booting from CD. If not, then I think such support can be added.

Ok, that would be a nice thing to have. I am ready to test this feature whenever it's out. I also have a [basic proposal](https://github.com/anatol/booster/issues/232#issuecomment-1737913983) for it.

**Comment by legionus** [comment]
I took fedora-live.iso and looked at what the system looks like. Well, I was too optimistic. make-initrd can boot a similar fedora-live, but it will not be possible to automatically detect the boot configuration and reproduce it.
