### ISSUE TITLE
Не могу добавить модули в alt linux вне /kernel/

### ISSUE THREAD

**Issue by vlad196** [osboot/make-initrd#34]
make-initrd не находит модули nvidia, которые находятся в /lib/modules/<kernel>/nVidia/

Если я помещу эти модули в /lib/modules/\<kernel\>/kernel/ 
они обнаруживаются.

Я использовал MODULES_LOAD, MODULES_ADD и MODULES_TRY_ADD

Я не совсем уверен проблема это или нет.
Так и задумано, что модули берутся только в папке /lib/modules/\<kernel\>/kernel/ (либо, по крайней мере не во всех каталогах)?

**Comment by antohami** [comment]
В пакете nvidia_glx_common есть файл /usr/share/make-initrd/features/nvidia/config.mk, в котором:
BLACKLIST_MODULES += nvidia nvidia-drm nvidia-modeset

Мантейнером пакета nvidia_glx_common так и задумано, чтобы проприетарный модуль ядра не попадал в initrd.
Удалите этот файл и попробуйте сделать make-initrd.

**Comment by vlad196** [comment]
> В пакете nvidia_glx_common есть файл /usr/share/make-initrd/features/nvidia/config.mk, в котором: BLACKLIST_MODULES += nvidia nvidia-drm nvidia-modeset
> 
> Мантейнером пакета nvidia_glx_common так и задумано, чтобы проприетарный модуль ядра не попадал в initrd. Удалите этот файл и попробуйте сделать make-initrd.

Может есть способ просто переназначить features через конфигурационные каталоги? 
Удалять или изменять часть пакета, это немного неудобно. Обновишь, и всё делать по новой.
