### ISSUE TITLE
/sbin/init -- ссылка на файл внутри оригинального корня

### ISSUE THREAD

**Issue by lo1ol** [osboot/make-initrd#4]
Не учтен случай, когда /sbin/init -- ссылка.

https://github.com/osboot/make-initrd/blob/9ce6d76f45c71333b4e1b13a0e7d1a23fb864982/data/lib/initrd/boot/scripts/sysinit#L8

Столкнулся с проблемой загрузки на Ubuntu 20.04: **[ -e /sbin/init ]** возвращает ошибку, что файл не существует. Проблема была в том, что */sbin/init* является ссылкой на элемент внутри оригинального корня (*/lib/systemd/systemd*). Флаг -e для команды test проверяет наличие файла по разыменованной  ссылке, но такого файла до монтирования корня не существует.

Проблему можно решить путем изменения строчки на
```bash
[ -e /sbin/init ] || [ -h /sbin/init ]
```

Ну Ubuntu 20.04 после таких изменений загрузиться удалось) Не тестировал работоспособность различных фич, но запуск системы в целом -- это кул!

**Comment by legionus** [comment]
> Проблему можно решить путем изменения строчки на

Вы правы. Возможно из-за этого у меня не получилось сходу загрузиться на федоре.

> Ну Ubuntu 20.04 после таких изменений загрузиться удалось) Не тестировал работоспособность различных фич, но запуск системы в целом -- это кул!

Ого! Это очень хорошие новости. Я постараюсь в ближайшее время зафиксировать этот результат в тестах.
