### ISSUE TITLE
Сохранение ссылок на дирректории

### ISSUE THREAD

**Issue by lo1ol** [osboot/make-initrd#5]
Теперь перешел на Red Os 7.3. При тестировании make-initd там обнаружил, что утилита не всегда сохраняет символические ссылки на директории. Например, вместо того, чтобы создавать ссылки *lib -> /usr/lib*, создается директория /lib.

Это не совсем корректное поведение т.к. пути до некоторых файлов в скриптах могут содержать через такие символические ссылки.

Вот как я решил проблему, чтобы образ initrd собирался корректно:
1. перенес создание основных директорий (bin, lib, usr) в скрипте make-initrd ближе к концу. Они создадутся, только если не были созданы до этого. Будем считать, что до этого они создавались с правильной структурой. Вышло так:
```bash
mkdir $verbose -p -- \
	./{,usr/}{,s}bin \
	./.initrd/{killall,uevent/events,uevent/queues/udev/.tmp} \
	./etc/{{initrd,modprobe.d,sysconfig},udev/rules.d} \
	./lib/{udev,initrd/{all,kmodules,post,pre}} \
	./var/{lock/subsys,log,run} \
	./{home/root,dev,mnt,root,run,proc,sys,tmp,bin,sbin} \
	./"$KERNEL_MODULES_DIR" \
	#

for d in lib etc; do
	if [ -d "/$d/modprobe.d" ]; then
		verbose "Copying files from $d/modprobe.d ..."
		find -L "/$d/modprobe.d" \
				-name '*.conf' \
			-exec cp -aLt ./etc/modprobe.d -- '{}' '+'
	fi

	if [ -d "/$d/udev/initramfs-rules.d" ]; then
		verbose "Copying files from /$d/udev/initramfs-rules.d ..."
		find -L "/$d/udev/initramfs-rules.d" \
				-name '*.rules' \
			-exec cp -aLt ./etc/udev/rules.d -- '{}' '+'
	fi
done
```

2. Поменял местами запуск put-files и put-tree. Это конечно скорее костыль, чем решение: put-tree должен сохранять структуру директорий, но почему-то этого не происходит. Вышло вот так:
```bash
printf '%s\n' "${FILES[@]}"      |xargs -r put-file .
printf '%s\n' "${LOCALFILES[@]}" |xargs -r put-file -r "$LOCALBUILDDIR" .
printf '%s\n' "${DIRS[@]}"       |xargs -r put-tree .
```

3. Дальше по мелочи:
```bash
mkdir /.initrd
mkfifo ./.initrd/telinit
mkfifo ./.initrd/rdshell

...

[ ".$BASH"    = ./bin/bash     ] || ln $verbose -s -- "$BASH"    ./bin/bash || :
[ ".$UDEVD"   = ./sbin/udevd   ] || ln $verbose -s -- "$UDEVD"   ./sbin/udevd || :
[ ".$UDEVADM" = ./sbin/udevadm ] || ln $verbose -s -- "$UDEVADM" ./sbin/udevadm || :
```

После этих изменений на red os все запустилось без проблем и структура директорий сохранилась:
![image](https://user-images.githubusercontent.com/32206454/113594429-5ef32b00-9640-11eb-99b0-cc7d30b0f3fa.png)

**Comment by lo1ol** [comment]
Возможно стоит копировать ссылочную структуру корневых директорий целиком, вместо того, чтобы делать mkdir. 

Это сделает make-initrd более портируемым, но, если честно, у меня такое ощущение, что почти все ссылочные директории создаются на этапе выполнения put-file

**Comment by lo1ol** [comment]
Ссылочную структуру можно сохранять примерно так

```bash
mkdir_save_symlinks()
{
    for dir in $@
    do
        if [ ! -e "$dir/.." ] && [ ! -h "$dir/.." ]
        then
            mkdir_save_symlinks "$(dirname $dir)"
        fi 
    done

    if [ ! -h "/$dir" ]
    then
        mkdir -p -- $dir
    else
       mkdir_save_symlinks ".$(readlink -f /$dir)"
       ln -s ".$(readlink -f /$dir)" $dir 
    fi
}

mkdir_save_symlinks {s}bin lib ...
```


Но у такого скрипта могут быть проблемы т.к. не обязательно ссылка создаётся на файл внутри той же директории.

В общем если идти таким путём, то надо убедиться, во всех этих нюансах

**Comment by legionus** [comment]
Я специально не пытался повторить файловую структу системы поскольку она довольно сильно отличается от дистрибутива к дистрибутиву. Я пытался получить нечто более менее стабильное после копирования в initramfs. Собственно для этого и создаются симлинки на bash, udevd, udevadm в определённом месте.

Почему понадобилась та же файловая структура, что и в системе ?

**Comment by legionus** [comment]
> Но надо убедиться, во всех нюансах

Системы могут отличаться не только `{{,s}bin,lib{,64}}`, но и структурой `/var`. Это довольно интересный вопрос.

**Comment by lo1ol** [comment]
Например, udev в дистрибутиве Red Os использует в качестве директории с конфигурацией /usr/lib/udev. У вас в скрипте такой директорией является /lib. В red os, директория /lib является ссылкой на /usr/lib. В результате выполнения make-initrd создаётся образ в котором отсутствует директория /usr/lib/udev и все ее содержимое перешло в /lib/udev

Например, в связи с этим возникают дальнейшие проблемы при загрузки с lvm. Это не единственная проблема. Также проблемы возникают с тем, что /usr/sbin/dmsetup на самом деле лежит в /sbin/setup и из-за этого возникают ошибки в udev/rules.d скриптах.

Да, от дистрибутива к дистрибутива эта ссылочная структура отличается. Но в том, то и дело, что make-initrd использует исполняемые файлы, собранные для специфичного дистрибутива, но при этом не сохраняет окружение, в котором его собирали. 

На мой взгляд, ничего не будет плохого в том, что make-initrd будет сохранять эту ссылочную структуру. Initrd же не делается универсальным для всех дистрибутивов, а собирается на нужной машине.

**Comment by legionus** [comment]
>  в дистрибутиве Red Os 

Если не секрет, что это за дистрибутив ?

**Comment by lo1ol** [comment]
https://redos.red-soft.ru/downloads/

**Comment by legionus** [comment]
По сути вы делаете симлинки для systemd-based дистрибутивов. В какой-то момент redhat перенёс всё из корня в `/usr`.

> Да, от дистрибутива к дистрибутива эта ссылочная структура отличается. Но в том, то и дело, что make-initrd использует исполняемые файлы, собранные для специфичного дистрибутива, но при этом не сохраняет окружение, в котором его собирали.

Вы правы насчёт исполняемых файлов, но также в фичах приходится писать скрипты и сервисы, которые должны быть переносимыми. Этого сложно добиться, если не знаешь какие пути будут в образах.

> На мой взгляд, ничего не будет плохого в том, что make-initrd будет сохранять эту ссылочную структуру. Initrd же не делается универсальным для всех дистрибутивов, а собирается на нужной машине.

Я не против этого подхода, но я пытаюсь понять какое правило тут должно действовать, чтобы не нарушать его в будущем.

**Comment by legionus** [comment]
> https://redos.red-soft.ru/downloads/

Ирония в том, что в этом дистрибутиве в документации в 3.1.4 `/{,s}bin` и `/usr/{,s}bin` [описаны](https://www.red-soft.ru/files/downloads/products/redos/redos_adm_manual_7_3.pdf) именно как разные каталоги :)

**Comment by lo1ol** [comment]
Я не настолько хорошо знаком с историей изменений red hat, да и в целом Linux систем:) Вам лучше знать, как сделать make-initrd максимально портируемым. 

Думаю, нам нужен такой алгоритм
1.  Восстановить оригинальную ссылочную структуру. 
2. Скопировать требуемые файлы из настоящего корня
3. Скопировать файлы из фич

На мой взгляд, так мы максимально воссоздадим исходную структуру директорий. 

На счёт директории var у меня тоже были проблемы. Сделать символические абсолютные ссылки на директории может быть хорошим решением? Естественно ссылки создаём,в соответсвии с оригинальным корнем.

**Comment by lo1ol** [comment]
> Ирония в том, что в этом дистрибутиве в документации в 3.1.4 `/{,s}bin` и `/usr/{,s}bin` [описаны](https://www.red-soft.ru/files/downloads/products/redos/redos_adm_manual_7_3.pdf) именно как разные каталоги :)

Дока с ошибкой значит:)

**Comment by legionus** [comment]
```bash
printf '%s\n' "${FILES[@]}"      |xargs -r put-file .
printf '%s\n' "${LOCALFILES[@]}" |xargs -r put-file -r "$LOCALBUILDDIR" .
printf '%s\n' "${DIRS[@]}"       |xargs -r put-tree .
```

C этим изменением есть проблема. Busybox на который рассчитывает runtime добавляется в DIRS:
https://github.com/osboot/make-initrd/blob/fcc7bd88547e9738821718e84582da1efeb417e2/tools/create-initrd#L55-L61
Сейчас содержимое DIRS имеет приоритет над остальным содержимым т.е. если уитилта есть в busybox, то она не будет скопирована. После предложенного изменения системные утилиты будут иметь приоритет.

Это повлияет как на размер образа, так и не его стабильность.

**Comment by lo1ol** [comment]
Понял. Может быть такое, что ссылочная структура создаваемая busybox как раз и ломает оригинальную? Может быть стоит конфигурировать busybox аккуратнее?

**Comment by legionus** [comment]
> Может быть такое, что ссылочная структура создаваемая busybox как раз и ломает оригинальную?

Оно не ломается, а создаётся такое какое находится в частности в фичах. При копировании уже системных утилит каталоги уже есть. Меняя порядок вы сначала сделали другие каталоги и симлинки из старых мест. Поэтому при копировании каталогов из фич, они легли внутрь симлинков.

> Может быть стоит конфигурировать busybox аккуратнее?

У него нет большой свободы в этом. Да и не в этом дело. Любой файл из фичи или откуда-либо с реальным путём приведёт к созданию реального каталога.

Выходом может быть создание необходимого дерева и симлинков до вот этого кода:
https://github.com/osboot/make-initrd/blob/fcc7bd88547e9738821718e84582da1efeb417e2/tools/create-initrd#L131-L133

По сути код:
https://github.com/osboot/make-initrd/blob/master/tools/create-initrd#L116-L124

и пытается создать структуру каталогов. Его нужно изменить таким образом, чтобы он создавал структуру каталогов не в лоб, как сейчас, а с учётом дистрибутива. Я пока не уверен, как это лучше сделать.

**Comment by legionus** [comment]
Прямо хоть хук создавай для того, чтобы создавать дистрибутивно-зависимую структуру каталогов.

**Comment by lo1ol** [comment]
Что насчет такого скрипта? У меня он создает нужное дерево.

```bash
mkdir_save_symlinks()
{
        local dir
        for dir in $@
        do
                local sub_dir="$(dirname "$dir")"

                if [ ! -e "$sub_dir" ] && [ ! -h "$sub_dir" ]
                then
                        mkdir_save_symlinks "$sub_dir"
                fi

                if [ ! -h "/$dir" ]
                then
                        mkdir $verbose -p -- "$dir"
                else
                        local follow_dir=".$(readlink -f "/$dir")"
                        mkdir_save_symlinks "$follow_dir"

                        local canon_path="$(realpath --relative-to="$sub_dir" "$follow_dir")"
                        ln -s "$canon_path" "$dir"
                fi
        done
}

mkdir_save_symlinks \
        {,usr/}{,s}bin \
        .initrd/{killall,uevent/events,uevent/queues/udev/.tmp} \
        etc/{{initrd,modprobe.d,sysconfig},udev/rules.d} \
        lib/{udev,initrd/{all,kmodules,post,pre}} \
        var/{lock/subsys,log,run} \
        {home/root,dev,mnt,root,run,proc,sys,tmp,bin,sbin} \
        "$KERNEL_MODULES_DIR" \
        #
```

Единственное, все-таки нужно добавить:
```bash

[ ".$BASH"    = ./bin/bash     ] || ln $verbose -s -- "$BASH"    ./bin/bash || :
[ ".$UDEVD"   = ./sbin/udevd   ] || ln $verbose -s -- "$UDEVD"   ./sbin/udevd || :
[ ".$UDEVADM" = ./sbin/udevadm ] || ln $verbose -s -- "$UDEVADM" ./sbin/udevadm || :
```

**Comment by legionus** [comment]
Вы меня опередили. Я нечто подобное начал писать. Да, до копирования файлов нужно пробежать по fhs, свериться с текущей системой и создать либо симлинк, либо реальный каталог. Тогда все файлы лягут в нужное место.

> Единственное, все-таки нужно добавить т.к. ссылки могут указывать сами на себя:

Ещё вчера я переделал этот кусок:

https://github.com/osboot/make-initrd/commit/f8f095b27766d8c9ef9e79a72508ce21839b1eb9

**Comment by legionus** [comment]
Только нужно вот такое `lib{,64}/{udev,initrd/{all,kmodules,post,pre}}` исправить. Пути `/lib64/udev` насколько мне известно не бывает. Правила лежат всегда в `/lib`. Ну а `/lib/initrd/...` это вообще внутренности make-initrd и этот путь прибит внутри скриптов.

**Comment by lo1ol** [comment]
а да, не заметил

**Comment by lo1ol** [comment]
вольете изменения?

**Comment by legionus** [comment]
получается вот такой набор:
```bash
mkdir_save_symlinks \
        {dev,mnt,root,run,proc,sys,tmp,{,usr/}{,s}bin,{,usr/}{share,lib{,32,x32,64}},var/{cache,lock/subsys,log,run}} \
        lib/{modules,udev,initrd/{all,kmodules,post,pre}} \
        etc/{{initrd,modprobe.d,sysconfig},udev/rules.d} \
        .initrd/{killall,uevent/events,uevent/queues/udev/.tmp} \
        home/root \
        "${KERNEL_MODULES_DIR#/}" \
        #
```

> вольете изменения?

Разумеется.

**Comment by legionus** [comment]
Можете проверить master ? ничего не забыто ?

**Comment by lo1ol** [comment]
Да, могу сейчас проверить на Ubuntu и чистом Red OS

**Comment by lo1ol** [comment]
на Ubuntu все шикарно создается) и загружается
![image](https://user-images.githubusercontent.com/32206454/113694615-a927eb00-96d8-11eb-9df9-44907a8989f8.png)

**Comment by legionus** [comment]
Hint: поскольку initrd может быть составным, а части сжатыми, то такие образы сложно просматривать (cpio не умеет составные образы). Для этого в make-initrd собирается утилита `initrd-ls`.

**Comment by lo1ol** [comment]
О, спасибо) про другие утилиты initrd-* тоже почитаю

**Comment by lo1ol** [comment]
В Red Os все тоже запустилось

**Comment by legionus** [comment]
Ок. Значит это тоже закрываем. Новый релиз я скоро подготовлю.
