### ISSUE TITLE
опции монтирования ro,loop срабатывают наоборот для фичи pipeline 

### ISSUE THREAD

**Issue by lo1ol** [osboot/make-initrd#6]
Сейчас тестирую свою фичу pipeline на Red OS. Обнаружил, что здесь установка опций перепутана:
https://github.com/osboot/make-initrd/blob/632b6a8839cfb0e4cfdb1d6ff44eda0404a8ccd1/features/pipeline/data/lib/pipeline/mountfs#L12-L14

Опции устанавливаются для реальных устройств, но не устанавливаются для файлов. Чтобы корректно работало, кажется должно быть так:
```bash
opts=
[ -c "$target" ] || [ -b "$target" ] ||
	opts='ro,loop'
```

Также еще столкнулся с такой проблемой, что при погрузки зависимостей фичи plymoyth выгружается конкретный шрифт из конкретной директории:
https://github.com/osboot/make-initrd/blob/632b6a8839cfb0e4cfdb1d6ff44eda0404a8ccd1/features/plymouth/config.mk#L16

в дистрибутиве Red OS этот шрифт располагается здесь $(DATADIR)/fonts/dejavu/DejaVuSans.ttf . Почему именно такой шрифт выгружается? Можно ли как-то определить какой точно шрифт используется и путь до него?

Извините, что я создаю обращения через issue, а не MR. Если вам будет удобнее, могу MR создавать. Просто мне кажется, что раз вы так хорошо знаете тонкости make-initrd вам будет проще самому правки сделать, чем объяснять мне, как надо)

**Comment by legionus** [comment]
> Опции устанавливаются для реальных устройств, но не устанавливаются для файлов. Чтобы корректно работало, кажется должно быть так:

Вы правы. Это опечатка.

**Comment by legionus** [comment]
> Почему именно такой шрифт выгружается?

plymouth очень капризная фича. Это пример дистрибутиво-зависмого кода (скорее всего). Штрифт нужен потому что иначе в образе не будет никакого шрифта (https://github.com/osboot/make-initrd/commit/a1e5a2729480bf0ec2d1211ec451d85998dce453). Я попробую придумать более портабильный способ определения пути до него (возможно `fc-list 'DejaVu Sans:style=Book' |cut -d: -f1` ?).

> Можно ли как-то определить какой точно шрифт используется и путь до него?

Я пока не знаю как определить, то что нужно конкретной теме. Сейчас список файлов это то что мне присылают дистрибутиво-строители из altlinux.

> Извините, что я создаю обращения через issue, а не MR.

Я не могу требовать от людей патчей :) Ваш интерес и ваша помощь в портировании и без того очень важна.

**Comment by lo1ol** [comment]
Я не нашел какой шрифт используется по умолчанию Plymouth, но команда ```fc-match -f '%{file}\n' 'DejaVuSans'``` возвращает верный путь на Red Os.

Может оставить вывод этой команды? Если проявится аналогичная проблема с шрифтами на другом ос, то можно придумать решение получше.

**Comment by legionus** [comment]
Я немного поправил фичу plymouth для улучшения портабильности.

**Comment by lo1ol** [comment]
https://github.com/osboot/make-initrd/commit/6cbfe8a9519999f20509802e70d42aca7891575c#r49804371

return только внутри функций работает

**Comment by legionus** [comment]
Да, это я промахнулся в последний момент. А в остальном работает ?

**Comment by lo1ol** [comment]
да, остальное все ок)
